services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - private

  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_BASE_URL=${API_BASE_URL}
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - MONGO_DATABASE=${MONGO_INITDB_DATABASE}
    secrets:
      - password_secret
      - jwt_secret
      - jwt_refresh_secret
      - jwt_reset_password_secret
    volumes:
      - ./src:/build_/apps/backend/src
    networks:
      - private

networks:
  private:
    driver: bridge

volumes:
  mongo_data:
    driver: local

secrets:
  password_secret:
    file: ./secrets/password_secret.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  jwt_refresh_secret:
    file: ./secrets/jwt_refresh_secret.txt
  jwt_reset_password_secret:
    file: ./secrets/jwt_reset_password_secret.txt
