/**
 * @enum Errors
 *
 * @description Errors
 */
export enum Errors {
  BAD_REQUEST = 1,
  RESOURCE_NOT_FOUND = 2,
  ROUTE_NOT_FOUND = 3,
  UNAUTHORIZED = 4,
  FORBIDDEN = 5,
  USER_ALREADY_EXISTS = 6,
  INVALID_CREDENTIALS = 7,
  INTERNAL_SERVER_ERROR = 8,
  INVALID_REFRESH_TOKEN = 9,
  INVALID_RESET_PASSWORD_TOKEN = 10,
  MONGO_CREATION_FAILED = 11,
  MONGO_DELETE_FAILED = 12,
  MONGO_UPDATE_FAILED = 13,
  USER_NOT_FOUND = 14,
}
